<?php

namespace AppBundle\Repository;

/**
 * ComicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComicRepository extends \Doctrine\ORM\EntityRepository
{
}
